version: '2'

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - front
      - back
  database:
    image: postgres:alpine3.14
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    networks:
      - back
  
  backend:
    build: ./lib_catalog
    networks:
      - back
    depends_on:
      - database

networks:
  back:
    driver: bridge  
  front:
    driver: bridge

