version: '3.8'

services:
  database:
    image: postgres:alpine3.14
    hostname: database
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    networks:
      - back
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  backend:
    build: ./lib_catalog
    hostname: backend
    networks:
      - back
      - front
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  web:
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - front
    depends_on:
      backend:
        condition: service_healthy

networks:
  back:
    name: back
    driver: bridge  
  front:
    name: front
    driver: bridge

